on: [ push, pull_request ]
name: mypy type checking
jobs:
    mypy:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        steps:
            - uses: actions/checkout@v3
            - run: pacman --noconfirm -Syu python python-pydantic mypy
            - name: run mypy
              run: mypy mirrortest/ --strict